apiVersion: v2
name: fitness-chart
description: Helm Chart for Fitness Tracker Application - Capstone Project
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: nanineelapu
keywords:
  - fitness
  - nodejs
  - mongodb
  - kubernetes

