apiVersion: v1
kind: ConfigMap
metadata:
  name: fitness-configmap
  labels:
    app: {{ .Values.app.name }}
    {{- include "fitness-tracker.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
