{{- if .Values.storageClass.create }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
  labels:
    {{- include "fitness-tracker.labels" . | nindent 4 }}
provisioner: {{ .Values.storageClass.provisioner }}
parameters:
  type: {{ .Values.storageClass.type }}
  fsType: {{ .Values.storageClass.fsType }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode }}
allowVolumeExpansion: {{ .Values.storageClass.allowVolumeExpansion }}
{{- end }}
